### ISSUE TITLE
tiktok videos don't render in xaringan

### ISSUE THREAD

**Issue by jvcasillas** [gadenbuie/tiktokrmd#1]
I am trying to include some tiktok videos in some slides and I am getting what looks like a a blockquote w/ no video. Reproducible example here: 

```
---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

    ```{r, tiktok, echo=F}
    library("tiktokrmd")
    tt_url <- "https://www.tiktok.com/@chelseaparlettpelleriti/video/6811647290709757189"
    tt <- tiktok_embed(tt_url)
    tt
    ```
```

And this is the output: 

<img width="1686" alt="Screen Shot 2021-03-16 at 18 30 15" src="https://user-images.githubusercontent.com/1747068/111388721-29cd6b80-8686-11eb-8ef6-16c96b2a40ad.png">

**Comment by gadenbuie** [comment]
This sounds like it might be related to a recent change in `rmarkdown`, can you try the suggestion in [this comment](https://github.com/yihui/xaringan/issues/293#issuecomment-761973964) in https://github.com/yihui/xaringan/issues/293?

It should also be fixed with the latest dev version of xaringan, which you can install from GitHub with remotes:

```r
remotes::install_github("yihui/xaringan")
```

I'm going to close this issue but please feel free to re-open it if the above doesn't solve your issue.

**Comment by jvcasillas** [comment]
That did it. Thank you once again.
